#!/usr/bin/env python3
"""R121 — assemble Layer 1 gold evidence-chain v1 (draft freeze artifact).

18 stable papers (5 pilot R098 + 3 C0 + 10 newly drafted from verification).
2 replacement slots (#9 traag, #20 zheng_social) are HELD — not in this freeze.

Fidelity scoring (per component, 3-level):
  1.0 FULL   — fully specified & recoverable from paper + executable materials
  0.5 PARTIAL — partly specified; missing parameter / ambiguous / requires assumption
  0.0 NONE   — not specified or not recoverable even with IO₃ materials

NOTE: gold_fidelity here is the GOLD-SIDE CEILING (best an agent could reach given
the paper's observability), NOT the agent's achieved score. Numeric target details
marked `pending` are flagged for human annotator confirmation (R098 adjudication
style) — they do not block the IO manipulation design.
"""
from __future__ import annotations
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "refine-logs" / "r121_gold_v1.json"

def comp(fidelity, rationale, **fields):
    d = dict(fields)
    d["gold_fidelity"] = fidelity
    d["fidelity_rationale"] = rationale
    return d

def paper(pid, title, domain, venue, year, task, stratum, annotator,
          data, sample, indicator, model, result, claim,
          expected_breaks, io_feasibility, notes=""):
    components = {"data_source": data, "sample": sample, "indicator": indicator,
                  "model": model, "result_table": result, "claim": claim}
    overall = round(sum(c["gold_fidelity"] for c in components.values()) / 6, 3)
    return {
        "paper_id": pid, "title": title, "domain": domain, "venue": venue,
        "year": year, "task_type": task, "observability_stratum": stratum,
        "annotator_id": annotator, "annotation_status": "draft_primary",
        "data_source": data, "sample": sample, "indicator": indicator,
        "model": model, "result_table": result, "claim": claim,
        "overall_gold_ecrf": overall,
        "expected_breaks": expected_breaks,
        "io_feasibility": io_feasibility,
        "notes": notes,
    }

GOLD = []

# ===== 8 CARRIED PAPERS (R098 + C0, consistency-checked) =====

GOLD.append(paper(
    "petersen2024", "The disruption index is biased by citation inflation",
    "SoS", "arXiv", 2023, "STRICT", "Low", "A/B",
    data=comp(1.0, "WoS+MAG named; SciSciNet public substitute used in R002",
              data_source="Web of Science + Microsoft Academic Graph",
              data_description="Citation network for disruption-index computation",
              access="public-substitute", provenance="SciSciNet (local, N=469,855) substitutes WoS"),
    sample=comp(1.0, "N and window explicit; R002 reproduced exactly",
                N=102550, time_window="2011-2015 (subset)", unit_of_analysis="paper",
                filter_rules=["ref_count 10-200", "author_count 1-25", "cit_5y 1-1000"]),
    indicator=comp(1.0, "CDp formula explicit in paper",
                   formula="CDp = (Ni - Nj)/(Ni + Nj + Nk); |CDp,5| with citation-inflation decomposition",
                   parameters=["5-year citation window", "ln(rp), ln(kp), ln(cp5) transforms"],
                   computation_steps=["build citation network", "compute CDp per paper", "regress on inflation terms"]),
    model=comp(1.0, "OLS spec explicit; R002 reproduced",
               spec_elements=["OLS", "year FE", "ln(rp)", "ln(kp)", "ln(cp5)"],
               estimator="OLS", coefficients={"ln_rp": -0.002322, "p": "<0.001"},
               fixed_effects=["year"]),
    result=comp(1.0, "R002 achieved D3=8/8 exact numerical identity",
                target_tables=["Table: regression coefs"],
                target_values=[{"label": "ln_rp_coef", "value": -0.002322, "tolerance": "exact"},
                               {"label": "sample_N", "value": 102550, "tolerance": "exact"},
                               {"label": "R2", "value": 0.120403, "tolerance": "exact"}],
                expected_direction="negative"),
    claim=comp(1.0, "Claim directly supported by negative coef",
               conclusion_claims=["CD systematically declines over time due to citation inflation, not true decline in innovation"],
               claim_scope="general", uncertainty="stated-qualifiers"),
    expected_breaks={"B1": {"likely": False, "component": "data_source", "note": "SciSciNet substitute is sanctioned"},
                     "B2": {"likely": True, "component": "result_table", "note": "hard-code reported coefs"},
                     "B3": {"likely": False, "component": "—", "note": "data available"},
                     "B4": {"likely": False, "component": "claim", "note": "claim-result distance small"}},
    io_feasibility={"IO1": {"feasible": "yes", "ceiling_components": ["indicator", "model", "claim"]},
                    "IO2": {"feasible": "yes", "ceiling_components": ["all"]},
                    "IO3": {"feasible": "yes", "ceiling_components": ["all"]},
                    "io_collapse": "none"},
    notes="Calibration anchor (Low floor). R002 D3=8/8. Carry-over from R098/C0."))

GOLD.append(paper(
    "wu2019_teams", "Teams vs. disruption (Wu et al. 2019)",
    "SoS", "Nature", 2019, "STRICT", "Low", "A/B",
    data=comp(1.0, "SciSciNet/MAG public substitute",
              data_source="Web of Science + Microsoft Academic Graph + USPTO + GitHub",
              data_description="Citation + authorship network", access="public-substitute",
              provenance="SciSciNet local"),
    sample=comp(1.0, "N explicit in paper",
                N=30000000, time_window="1954-2000s", unit_of_analysis="team-paper",
                filter_rules=["complete citation data", "team-size deciles"]),
    indicator=comp(1.0, "Disruption index CD explicit",
                   formula="CD = (Ni - Nj)/(Ni + Nj + Nk)",
                   parameters=["team-size deciles", "D-index by decile"],
                   computation_steps=["build citation network", "compute CD per paper", "group by team size"]),
    model=comp(0.5, "Spec describable; direction is the stress point (R001 direction NEGATIVE)",
               spec_elements=["OLS", "year FE", "team_size_deciles", "mean_D_by_group"],
               estimator="OLS", coefficients={"team_size_coef": -0.03, "direction": "NEGATIVE (R001 reproduced coef=-0.0093)"},
               fixed_effects=["year"]),
    result=comp(0.5, "Numerical targets exist but direction-negative is the known failure mode",
                target_tables=["Table: Mean D-index by team-size decile"],
                target_values=[{"label": "small_teams_D", "value": 0.04, "tolerance": "approx"},
                               {"label": "large_teams_D", "value": -0.02, "tolerance": "approx"}],
                expected_direction="negative"),
    claim=comp(0.0, "Claim-direction is the known component-localized FAILURE (R001)",
               conclusion_claims=["Large teams develop existing science", "Small teams disrupt science"],
               claim_scope="general", uncertainty="stated-qualifiers"),
    expected_breaks={"B1": {"likely": False, "component": "—", "note": "data public"},
                     "B2": {"likely": False, "component": "—", "note": "—"},
                     "B3": {"likely": False, "component": "—", "note": "—"},
                     "B4": {"likely": True, "component": "claim", "note": "agent may assert disruption direction incorrectly"}},
    io_feasibility={"IO1": {"feasible": "yes", "ceiling_components": ["indicator", "model"]},
                    "IO2": {"feasible": "yes", "ceiling_components": ["all"]},
                    "IO3": {"feasible": "yes", "ceiling_components": ["all"]},
                    "io_collapse": "none"},
    notes="Known component-localized failure (Model/Claim=0, Data/Sample/Indicator=1). R001 coef=-0.0093 (direction NEGATIVE). Motivates v7.2."))

GOLD.append(paper(
    "park2023_disruptive", "Papers and patents are becoming less disruptive over time",
    "SoS", "Nature", 2023, "STRICT", "Low", "A/B",
    data=comp(1.0, "MAG/SciSciNet public", data_source="Microsoft Academic Graph + USPTO + SciSciNet",
              data_description="Citation network 1945-2010", access="public", provenance="SciSciNet local"),
    sample=comp(1.0, "N explicit; R004 reproduced", N=469855, time_window="1945-2010",
                unit_of_analysis="paper", filter_rules=["require CD score", "drop_na"]),
    indicator=comp(1.0, "CD5 index explicit",
                   formula="CD5 = (Ni - Nj)/(Ni + Nj + Nk), 5-year window",
                   parameters=["5-year citation window"], computation_steps=["compute CD5 per paper", "groupby year mean"]),
    model=comp(1.0, "Descriptive aggregation; R004 reproduced",
               spec_elements=["descriptive", "groupby year", "mean CD5"], estimator="descriptive",
               coefficients={"cd_1945_mean": 0.03598, "cd_2010_mean": 0.00119}, fixed_effects=[]),
    result=comp(1.0, "R004 achieved D3=6/6 exact", target_tables=["Fig: CD5 mean by year"],
                target_values=[{"label": "cd_1945_mean", "value": 0.03597944, "tolerance": "exact"},
                               {"label": "cd_2010_mean", "value": 0.00119062, "tolerance": "exact"},
                               {"label": "overall_mean", "value": 0.005724, "tolerance": "exact"}],
                expected_direction="negative"),
    claim=comp(1.0, "Claim supported by decline trend",
               conclusion_claims=["Papers and patents are becoming less disruptive over time"],
               claim_scope="general", uncertainty="stated-qualifiers"),
    expected_breaks={"B1": {"likely": False, "component": "—"}, "B2": {"likely": True, "component": "result_table", "note": "hard-code means"},
                     "B3": {"likely": False, "component": "—"}, "B4": {"likely": False, "component": "—"}},
    io_feasibility={"IO1": {"feasible": "yes"}, "IO2": {"feasible": "yes"}, "IO3": {"feasible": "yes"}, "io_collapse": "none"},
    notes="R004 D3=6/6. STRICT calibration."))

GOLD.append(paper(
    "bentley2023_disruption", "Is disruption decreasing, or is it accelerating?",
    "SoS", "Advances in Complex Systems", 2023, "STRICT", "Low", "A/B",
    data=comp(1.0, "SciSciNet public (same as Park2023)", data_source="SciSciNet", data_description="Citation network 1945-2010",
              access="public", provenance="SciSciNet local"),
    sample=comp(1.0, "N explicit; R007 reproduced", N=469855, time_window="1945-2010", unit_of_analysis="paper",
                filter_rules=["require CD score", "require citations"]),
    indicator=comp(1.0, "Citation-weighted mCD5 explicit",
                   formula="mCD5(t) = Σ(cit_i * CD5_i) / Σ(cit_i)",
                   parameters=["citation weighting"], computation_steps=["compute CD5", "weight by citations", "groupby year"]),
    model=comp(1.0, "Weighted descriptive; R007 reproduced",
               spec_elements=["descriptive", "citation-weighted", "groupby year"], estimator="descriptive",
               coefficients={"weighted_cd_1945": 0.07699, "weighted_cd_2010": 0.00076}, fixed_effects=[]),
    result=comp(1.0, "R007 achieved D3=9/9 exact", target_tables=["Fig: weighted CD5 by year"],
                target_values=[{"label": "weighted_cd_1945_mean", "value": 0.07698916, "tolerance": "exact"},
                               {"label": "weighted_cd_2010_mean", "value": 0.00076, "tolerance": "approx"}],
                expected_direction="mixed"),
    claim=comp(1.0, "Weighted CD close to zero since ~1970, modest increase since 2000",
               conclusion_claims=["CD5 decline (Park2023) is partly an artifact of exponential growth; weighted CD flat/accelerating since 1970"],
               claim_scope="general", uncertainty="stated-qualifiers"),
    expected_breaks={"B1": {"likely": False, "component": "—"}, "B2": {"likely": True, "component": "result_table"},
                     "B3": {"likely": False, "component": "—"}, "B4": {"likely": False, "component": "—"}},
    io_feasibility={"IO1": {"feasible": "yes"}, "IO2": {"feasible": "yes"}, "IO3": {"feasible": "yes"}, "io_collapse": "none"},
    notes="R007 D3=9/9. STRICT calibration."))

# arts2021, funk2017, maddi2024, bikard2013 from R098 (carry over)
GOLD.append(paper(
    "arts2021", "Natural Language Processing to Identify the Structure of Innovation in Patent Claims",
    "IS_Innovation", "Research Policy", 2021, "METHOD", "Medium", "A/B",
    data=comp(1.0, "USPTO public", data_source="USPTO patent claims + PatentsView",
              data_description="Patent claims for NLP-indicator extraction", access="public", provenance="USPTO"),
    sample=comp(1.0, "10-step preprocessing P1-P10 explicit", N="unknown", time_window="USPTO coverage",
                unit_of_analysis="patent claim", filter_rules=["P1-P10 preprocessing steps"]),
    indicator=comp(0.5, "10 indicators; known aggregation-formula bug at lines 233-236 (|set|+Σui vs |set|*(1+Σui))",
                   formula="I1-I5 novelty (5 formulas correct); I6-I9 reuse (bug); I5/I10 cosine-similarity",
                   parameters=["n-gram window", "cosine binary TF"], computation_steps=["tokenize", "n-gram extract", "cosine sim"]),
    model=comp(1.0, "METHOD — descriptive aggregation, no regression", spec_elements=["descriptive aggregation"],
               estimator="none", coefficients={}, fixed_effects=[]),
    result=comp(0.5, "Cosine indicators match within 1-5% (R003); reuse indicators have known bug",
                target_tables=["Tables: indicator values"], target_values=[{"label": "cosine_match", "value": "1-5%", "tolerance": "approx"}],
                expected_direction="none"),
    claim=comp(0.5, "Claim-result distance moderate (aggregation bug under-supports reuse claims)",
               conclusion_claims=["NLP indicators identify structure of innovation in patent claims; novelty vs reuse dimensions"],
               claim_scope="descriptive", uncertainty="stated-qualifiers"),
    expected_breaks={"B1": {"likely": True, "component": "indicator", "note": "cosine-sim proxy"},
                     "B2": {"likely": True, "component": "indicator", "note": "formula hard-code"},
                     "B3": {"likely": False, "component": "—"}, "B4": {"likely": False, "component": "—"}},
    io_feasibility={"IO1": {"feasible": "yes"}, "IO2": {"feasible": "yes"}, "IO3": {"feasible": "yes"}, "io_collapse": "none"},
    notes="R003 component diagnosis; known localized break at Indicator. Carry-over from R098."))

GOLD.append(paper(
    "funk2017", "A Dynamic Network Measure of Technological Change",
    "IS_Innovation", "PLoS ONE", 2017, "STRICT", "High", "A/B",
    data=comp(1.0, "NBER + Dataverse public", data_source="NBER US Patent Citations + Patent Network Dataverse (Li et al.)",
              data_description="Patent citation network", access="public", provenance="Dataverse"),
    sample=comp(0.5, "Exact N pending adjudicator (Table 1)", N="pending", time_window="5-year citation window (CD5/mCD5)",
                unit_of_analysis="patent", filter_rules=["14 NBER tech categories", "university/federal/commercial subsets"]),
    indicator=comp(1.0, "CDt/mCDt explicit; cdindex.info code public",
                   formula="CDt Eq.(1), range [-1,1], mean 0.07 SD 0.23; mCDt impact-weighted, mean 0.31 SD 1.75",
                   parameters=["-2 correction in numerator (line 455)", "impact weighting"],
                   computation_steps=["build graph G(V1,V2,V3,E)", "compute CDt", "weight to mCDt"]),
    model=comp(1.0, "OLS + Negative Binomial", spec_elements=["OLS", "NegBinom", "commercial engagement", "federal support"],
               estimator="negative-binomial", coefficients={"CD5_impact_r": 0.03, "p": "<0.001"}, fixed_effects=[]),
    result=comp(1.0, "R103 IO3=0.825; numerical targets in Table 1/3",
                target_tables=["Table 1/3"], target_values=[{"label": "CD5_impact_r", "value": 0.03, "tolerance": "approx"}],
                expected_direction="positive"),
    claim=comp(0.5, "Claim-result distance small-moderate",
               conclusion_claims=["CDt/mCDt measure technological change direction+magnitude; engagement & federal support positively related to disruption"],
               claim_scope="general", uncertainty="stated-qualifiers"),
    expected_breaks={"B1": {"likely": True, "component": "sample", "note": "Dataverse subset substitution"},
                     "B2": {"likely": True, "component": "indicator", "note": "hard-code reported index values"},
                     "B3": {"likely": False, "component": "—"}, "B4": {"likely": False, "component": "—"}},
    io_feasibility={"IO1": {"feasible": "yes"}, "IO2": {"feasible": "yes"}, "IO3": {"feasible": "yes"}, "io_collapse": "none"},
    notes="Cleanest IO3 anchor. R103: IO1 0.500 → IO3 0.825. Carry-over from R098."))

GOLD.append(paper(
    "maddi2024", "On the Peer Review Reports: Does Size Matter?",
    "Management_Strategy", "Scientometrics (Springer)", 2024, "METHOD", "Low", "A/B",
    data=comp(0.0, "Publons private/defunct; bespoke WoS-matched drop not public",
              data_source="Publons (reviewer-report length) + Web of Science (citations)",
              data_description="Matched Publons×WoS dataset", access="private", provenance="author data drop (Publons sunset 2022-23)"),
    sample=comp(0.5, "N explicit but not reconstructable", N=57482, time_window="2009-2020 (adjudicator confirm)",
                unit_of_analysis="publication", filter_rules=["IQR outlier removal on report length"]),
    indicator=comp(1.0, "Report-length measure explicit",
                   formula="IV = reviewer-report word count; DV = citations received",
                   parameters=["IQR outlier control"], computation_steps=["count words", "IQR filter", "match to WoS citations"]),
    model=comp(1.0, "Robust regression spec describable",
               spec_elements=["robust regression", "OLS-family", "confound controls"], estimator="robust-regression",
               coefficients={"threshold": 947, "direction": "positive"}, fixed_effects=[]),
    result=comp(0.5, "Threshold (947 words) explicit; exact coefs pending",
                target_tables=["regression tables"], target_values=[{"label": "threshold_words", "value": 947, "tolerance": "approx"}],
                expected_direction="positive"),
    claim=comp(0.5, "Claim-result distance small",
               conclusion_claims=["Longer reviewer reports → more citations, with a 947-word threshold"],
               claim_scope="sample-specific", uncertainty="stated-qualifiers"),
    expected_breaks={"B1": {"likely": True, "component": "data_source", "note": "WoS-only / open-review proxy for Publons"},
                     "B2": {"likely": True, "component": "result_table", "note": "coefficient hard-code"},
                     "B3": {"likely": True, "component": "data_source", "note": "synthesis if no substitute corpus"},
                     "B4": {"likely": False, "component": "—"}},
    io_feasibility={"IO1": {"feasible": "yes", "ceiling_components": ["indicator", "model", "claim"]},
                    "IO2": {"feasible": "partial", "ceiling_components": ["indicator", "model"], "rationale": "sample not reconstructable"},
                    "IO3": {"feasible": "partial", "ceiling_components": ["indicator", "model"], "rationale": "collapses to IO2 — Publons defunct"},
                    "io_collapse": "IO2_IO3"},
    notes="R103 confirmed flat 0.500/0.500/0.500 — negative-result boundary (R153 candidate). STRICT impossible; METHOD/DATA-SUB only."))

GOLD.append(paper(
    "bikard2013", "Exploring Tradeoffs in the Organization of Scientific Work",
    "Management_Strategy", "Management Science", 2013, "DATA-SUB", "High", "A/B",
    data=comp(0.0, "MIT 661-faculty dataset private, no public substitute at faculty level",
              data_source="Academic publications of 661 MIT faculty scientists",
              data_description="30-year MIT faculty publication/citation records", access="private",
              provenance="MIT-internal"),
    sample=comp(0.5, "N explicit but not reconstructable", N=661, time_window="1976-2006",
                unit_of_analysis="scientist-year", filter_rules=["MIT-internal disambiguation"]),
    indicator=comp(1.0, "Collaboration + credit measures explicit",
                   formula="Co-authorship collaboration; credit-allocation fraction α; citation probability quartile regression",
                   parameters=["credit fraction α"], computation_steps=["compute collaboration", "compute credit", "quartile regression"]),
    model=comp(1.0, "Individual + year FE regression explicit",
               spec_elements=["individual FE", "year FE", "quartile regression"], estimator="OLS-FE",
               coefficients={"collab_credit": "positive", "coauthors_threshold": 4}, fixed_effects=["individual", "year"]),
    result=comp(0.5, "Directional results explicit; exact coefs pending",
                target_tables=["regression tables"], target_values=[{"label": "collab_credit_dir", "value": "positive", "tolerance": "direction"},
                               {"label": "coauthor_threshold", "value": 4, "tolerance": "approx"}],
                expected_direction="positive"),
    claim=comp(0.5, "Claim-result distance moderate — cross-institution generalization from single MIT sample",
               conclusion_claims=["Tradeoff between collaboration and reward at individual faculty level; credit not simply divided among authors"],
               claim_scope="general", uncertainty="stated-qualifiers"),
    expected_breaks={"B1": {"likely": True, "component": "sample", "note": "SciSciNet/institute proxy for MIT faculty — highest risk"},
                     "B2": {"likely": False, "component": "—"}, "B3": {"likely": False, "component": "—"},
                     "B4": {"likely": True, "component": "claim", "note": "cross-institution claim stretch from single-institution data"}},
    io_feasibility={"IO1": {"feasible": "yes", "ceiling_components": ["indicator", "model", "claim"]},
                    "IO2": {"feasible": "partial", "ceiling_components": ["indicator", "model"], "rationale": "sample not reconstructable"},
                    "IO3": {"feasible": "partial", "ceiling_components": ["indicator", "model"], "rationale": "no original code/data → IO3 collapses to IO2"},
                    "io_collapse": "IO2_IO3"},
    notes="Highest break-probability paper. R103: IO1 0.500 → IO3 0.975 (large slope despite data absence — agent reconstructs with substitutes). Boundary case by design."))

# ===== 10 NEW STABLE PAPERS (drafted from verification) =====

GOLD.append(paper(
    "ke2015_sleeping_beauties", "Defining and identifying Sleeping Beauties in science",
    "SoS", "PNAS", 2015, "METHOD", "Medium", "A/B",
    data=comp(0.0, "WoS+APS licensed, not public", data_source="Web of Science + APS",
              data_description="22M-paper citation corpus", access="private", provenance="Clarivate/APS licensed"),
    sample=comp(0.5, "Corpus described; N=22M papers", N=22000000, time_window="1900-2013",
                unit_of_analysis="paper", filter_rules=["citation-network construction"]),
    indicator=comp(0.5, "Sleeping-beauty Bcriterion parameterization; substitute SciSciNet needed",
                   formula="Beckendorf Bcriterion ( Beautycriterion); citation-delay + sudden-awakening metrics",
                   parameters=["awakening threshold"], computation_steps=["build citation network", "detect delayed citation burst"]),
    model=comp(1.0, "METHOD — descriptive + top-100 SB identification", spec_elements=["descriptive", "top-100 ranking"],
               estimator="descriptive", coefficients={}, fixed_effects=[]),
    result=comp(0.5, "Top-100 SB lists at qke.github.io (result tables, not raw data)",
                target_tables=["Top-100 Sleeping Beauties list"], target_values=[{"label": "top100_SB", "value": "list", "tolerance": "set-membership"}],
                expected_direction="none"),
    claim=comp(0.5, "Claim-result distance moderate",
               conclusion_claims=["Sleeping Beauties (delayed-impact papers) are a real citation-dynamics phenomenon, identifiable via Bcriterion"],
               claim_scope="descriptive", uncertainty="stated-qualifiers"),
    expected_breaks={"B1": {"likely": True, "component": "data_source", "note": "SciSciNet/MAG substitute for WoS+APS"},
                     "B2": {"likely": False, "component": "—"}, "B3": {"likely": False, "component": "—"},
                     "B4": {"likely": False, "component": "—"}},
    io_feasibility={"IO1": {"feasible": "yes", "ceiling_components": ["indicator", "claim"]},
                    "IO2": {"feasible": "partial", "ceiling_components": ["indicator", "model"], "rationale": "licensed data inaccessible"},
                    "IO3": {"feasible": "partial", "ceiling_components": ["indicator", "model"], "rationale": "substitute SciSciNet required → boundary"},
                    "io_collapse": "IO2_IO3 (data-licensed)"},
    notes="Identity corrected from ke2023/Scientometrics. IO3 boundary (licensed data). Verification appendix."))

GOLD.append(paper(
    "sun2023_ranking_mobility", "Ranking mobility and impact inequality in early academic careers",
    "SoS", "JASIST", 2023, "DATA-SUB", "Medium", "A/B",
    data=comp(1.0, "Public career-history data", data_source="Public career-history dataset (MAG-derived)",
              data_description="Author career trajectories", access="public", provenance="MAG/OpenAlex"),
    sample=comp(1.0, "Career reconstruction describable", N="pending", time_window="early-career window",
                unit_of_analysis="author", filter_rules=["career reconstruction", "ranking bins"]),
    indicator=comp(0.5, "Ranking-mobility + impact-inequality metrics; exact params pending",
                   formula="Ranking mobility (transition rates between impact quantiles); inequality measures",
                   parameters=["quantile bins"], computation_steps=["reconstruct careers", "compute rankings", "transition rates"]),
    model=comp(0.5, "Spec describable; exact estimator pending", spec_elements=["descriptive", "mobility indices"],
               estimator="descriptive", coefficients={}, fixed_effects=[]),
    result=comp(0.5, "Mobility/inequality values pending", target_tables=["Tables: mobility indices"],
                target_values=[{"label": "mobility_index", "value": "pending", "tolerance": "pending"}], expected_direction="mixed"),
    claim=comp(0.5, "Claim-result distance moderate", conclusion_claims=["Ranking mobility and impact inequality characterize early-career dynamics"],
               claim_scope="descriptive", uncertainty="stated-qualifiers"),
    expected_breaks={"B1": {"likely": True, "component": "sample", "note": "career reconstruction substitute"},
                     "B2": {"likely": False, "component": "—"}, "B3": {"likely": False, "component": "—"},
                     "B4": {"likely": True, "component": "claim", "note": "generalization stretch"}},
    io_feasibility={"IO1": {"feasible": "yes"}, "IO2": {"feasible": "yes"}, "IO3": {"feasible": "partial", "rationale": "no original code; agent writes own"},
                    "io_collapse": "none"},
    notes="DATA-SUB pathway; tests Sample-component. Numeric details pending annotator."))

GOLD.append(paper(
    "deng2023_enhancing_disruption", "Enhancing the robustness of the disruption metric against noise",
    "SoS", "Scientometrics", 2023, "METHOD", "Medium", "A/B",
    data=comp(0.5, "Original citation network licensed; SciSciNet substitute",
              data_source="Citation network (WoS/Scopus-class, licensed)",
              data_description="Citation network for CD5 robustness testing", access="private-substitute",
              provenance="SciSciNet substitute (r008 pathway)"),
    sample=comp(1.0, "SciSciNet substitute usable", N=469855, time_window="1945-2010",
                unit_of_analysis="paper", filter_rules=["require CD5"]),
    indicator=comp(0.5, "Robustness-variant CD5 formulas; edge-removal hot-spot refs",
                   formula="CD5 recompute after edge-removal to hot-spot references; robustness delta",
                   parameters=["hot-spot ref threshold"], computation_steps=["compute CD5", "remove hot-spot edges", "recompute CD5 delta"]),
    model=comp(1.0, "METHOD — robustness comparison", spec_elements=["descriptive", "edge-removal ablation"],
               estimator="descriptive", coefficients={}, fixed_effects=[]),
    result=comp(0.5, "Robustness deltas pending", target_tables=["Tables: CD5 robustness deltas"],
                target_values=[{"label": "robustness_delta", "value": "pending", "tolerance": "pending"}], expected_direction="mixed"),
    claim=comp(0.5, "Claim-result distance moderate",
               conclusion_claims=["Disruption metric can be made robust against citation noise via edge-removal"],
               claim_scope="descriptive", uncertainty="stated-qualifiers"),
    expected_breaks={"B1": {"likely": True, "component": "data_source", "note": "SciSciNet substitute"},
                     "B2": {"likely": False, "component": "—"}, "B3": {"likely": False, "component": "—"},
                     "B4": {"likely": False, "component": "—"}},
    io_feasibility={"IO1": {"feasible": "yes"}, "IO2": {"feasible": "yes"}, "IO3": {"feasible": "partial", "rationale": "agent-written code on SciSciNet substitute; boundary"},
                    "io_collapse": "none"},
    notes="IO3 demoted to boundary (data not actually public). Complements petersen2024 at Medium."))

GOLD.append(paper(
    "schaper2025_frontier", "Not like the others: Frontier scientists for inventive performance",
    "IS_Innovation", "Research Policy", 2025, "DATA-SUB", "Medium", "A/B",
    data=comp(0.5, "Raw feeds public (PubMed+USPTO); KU Leuven author-inventor linkage private",
              data_source="PubMed + US biomedical patents (USPTO) + KU Leuven/ECOOM disambiguation + BvD Orbis",
              data_description="Author-inventor linked career data", access="partial",
              provenance="PubMed/USPTO public; linkage private"),
    sample=comp(0.5, "Sample describable; linkage unreconstructable", N="pending", time_window="biomedical careers",
                unit_of_analysis="scientist", filter_rules=["author-inventor disambiguation"]),
    indicator=comp(0.5, "Frontier-scientist identification metrics; exact formula pending",
                   formula="Inventive-performance indicator distinguishing frontier scientists",
                   parameters=["frontier threshold"], computation_steps=["link authors to inventors", "compute performance metric"]),
    model=comp(0.5, "Spec describable; pending", spec_elements=["regression", "frontier-scientist IV"],
               estimator="OLS", coefficients={}, fixed_effects=[]),
    result=comp(0.5, "Frontier-performance coefficients pending", target_tables=["Tables: frontier-scientist effects"],
                target_values=[{"label": "frontier_effect", "value": "pending", "tolerance": "pending"}], expected_direction="positive"),
    claim=comp(0.5, "Claim-result distance moderate",
               conclusion_claims=["Frontier scientists (inventive performers) differ systematically from peers"],
               claim_scope="general", uncertainty="stated-qualifiers"),
    expected_breaks={"B1": {"likely": True, "component": "sample", "note": "PatentsView/PATSTAT substitute for KU Leuven linkage"},
                     "B2": {"likely": False, "component": "—"}, "B3": {"likely": False, "component": "—"},
                     "B4": {"likely": True, "component": "claim", "note": "generalization without proprietary linkage"}},
    io_feasibility={"IO1": {"feasible": "yes"}, "IO2": {"feasible": "partial", "rationale": "linkage unreconstructable"},
                    "IO3": {"feasible": "partial", "rationale": "collapses without proprietary linkage"}, "io_collapse": "IO2_IO3"},
    notes="Boundary case alongside bikard2013. R121 to fetch PDF to confirm if linkage released."))

GOLD.append(paper(
    "galuez2023_technology_transfer", "Scientific literature cited in patents: A Technology Transfer analysis",
    "IS_Innovation", "PLoS ONE", 2023, "METHOD", "Medium", "A/B",
    data=comp(1.0, "USPTO public", data_source="USPTO patents + cited scientific literature",
              data_description="Patent-to-paper citation links", access="public", provenance="USPTO"),
    sample=comp(1.0, "USPTO sample describable", N="pending", time_window="USPTO coverage",
                unit_of_analysis="patent-paper citation pair", filter_rules=["citation-link extraction"]),
    indicator=comp(0.5, "Tech-transfer classification metrics; exact formula pending",
                   formula="Technology-transfer indicator from patent-citation patterns",
                   parameters=["classification threshold"], computation_steps=["extract patent citations", "classify transfer type"]),
    model=comp(1.0, "METHOD — descriptive classification", spec_elements=["descriptive", "classification"],
               estimator="descriptive", coefficients={}, fixed_effects=[]),
    result=comp(0.5, "Classification rates pending", target_tables=["Tables: transfer-type rates"],
                target_values=[{"label": "transfer_rate", "value": "pending", "tolerance": "pending"}], expected_direction="none"),
    claim=comp(0.5, "Claim-result distance moderate",
               conclusion_claims=["Patent-cited scientific literature reveals technology-transfer patterns"],
               claim_scope="descriptive", uncertainty="stated-qualifiers"),
    expected_breaks={"B1": {"likely": True, "component": "indicator", "note": "classification proxy"},
                     "B2": {"likely": False, "component": "—"}, "B3": {"likely": False, "component": "—"},
                     "B4": {"likely": False, "component": "—"}},
    io_feasibility={"IO1": {"feasible": "yes"}, "IO2": {"feasible": "yes"}, "IO3": {"feasible": "partial", "rationale": "no original code; agent writes own on USPTO"},
                    "io_collapse": "none"},
    notes="IS METHOD; USPTO pipeline parallel to arts2021."))

GOLD.append(paper(
    "vasarhelyi2023_who_benefits", "Who benefits from altmetrics? The effect of team gender composition",
    "IS_Innovation", "arXiv (JASIST unconfirmed)", 2023, "DATA-SUB", "Medium", "A/B",
    data=comp(0.0, "Altmetric.com API-gated + WoS licensed", data_source="Altmetric.com + Web of Science",
              data_description="Altmetrics + citation matched corpus", access="api-gated",
              provenance="Altmetric.com (license) + WoS (license)"),
    sample=comp(0.5, "CEM-matched sample describable; data inaccessible", N="pending", time_window="altmetrics coverage window",
                unit_of_analysis="paper", filter_rules=["Coarsened Exact Matching on gender composition"]),
    indicator=comp(0.5, "Gender-composition + online-visibility metrics; exact pending",
                   formula="Team gender composition × online visibility → citation impact (CEM quasi-experimental)",
                   parameters=["CEM coarsening bins"], computation_steps=["compute gender composition", "CEM match", "estimate treatment effect"]),
    model=comp(0.5, "CEM quasi-experimental design describable", spec_elements=["Coarsened Exact Matching", "treatment-effect estimation"],
               estimator="CEM", coefficients={}, fixed_effects=[]),
    result=comp(0.5, "Gender-composition treatment effects pending", target_tables=["Tables: CEM treatment effects"],
                target_values=[{"label": "gender_treatment_effect", "value": "pending", "tolerance": "pending"}], expected_direction="mixed"),
    claim=comp(0.5, "Claim-result distance moderate",
               conclusion_claims=["Team gender composition affects who benefits from online visibility"],
               claim_scope="sample-specific", uncertainty="stated-qualifiers"),
    expected_breaks={"B1": {"likely": True, "component": "data_source", "note": "open altmetrics substitute for Altmetric.com"},
                     "B2": {"likely": True, "component": "result_table", "note": "coefficient hard-code"},
                     "B3": {"likely": False, "component": "—"}, "B4": {"likely": False, "component": "—"}},
    io_feasibility={"IO1": {"feasible": "yes"}, "IO2": {"feasible": "partial", "rationale": "CEM design describable but data inaccessible"},
                    "IO3": {"feasible": "partial", "rationale": "substitute altmetrics corpus required → boundary"}, "io_collapse": "IO2_IO3 (data-licensed)"},
    notes="IO3 demoted to boundary (Altmetric.com API-gated). Reclassified STRICT→DATA-SUB. Promote-to-High dropped."))

GOLD.append(paper(
    "donner2024_data_inaccuracy", "Data inaccuracy quantification and uncertainty propagation for bibliometric indicators",
    "Management_Strategy", "Research Evaluation", 2024, "METHOD", "Medium", "A/B",
    data=comp(0.5, "Public Zenodo CSV (error column only, 1.8KB); full WoS licensed",
              data_source="Web of Science + citation-count-error dataset (Zenodo)",
              data_description="Bibliometric indicators + citation-count errors", access="partial",
              provenance="Zenodo 10.5281/zenodo.13969973 (error CSV); WoS licensed"),
    sample=comp(1.0, "Error dataset public; sample describable", N="pending", time_window="WoS coverage",
                unit_of_analysis="paper", filter_rules=["citation-count error classification"]),
    indicator=comp(0.5, "Inaccuracy quantification + uncertainty propagation; exact formulas pending",
                   formula="Citation-count error distribution + Monte-Carlo uncertainty propagation to bibliometric indicators",
                   parameters=["error model", "MC iterations"], computation_steps=["estimate error distribution", "propagate uncertainty via MC"]),
    model=comp(0.5, "Bayesian regression + Monte-Carlo pipeline; pending", spec_elements=["Bayesian regression", "Monte-Carlo propagation"],
               estimator="bayesian", coefficients={}, fixed_effects=[]),
    result=comp(0.5, "Uncertainty bounds pending", target_tables=["Tables: uncertainty bounds"],
                target_values=[{"label": "uncertainty_bound", "value": "pending", "tolerance": "pending"}], expected_direction="mixed"),
    claim=comp(0.5, "Claim-result distance moderate",
               conclusion_claims=["Bibliometric indicators carry quantifiable uncertainty from citation-count errors"],
               claim_scope="descriptive", uncertainty="stated-qualifiers"),
    expected_breaks={"B1": {"likely": False, "component": "—"}, "B2": {"likely": True, "component": "model", "note": "spec hard-code"},
                     "B3": {"likely": False, "component": "—"}, "B4": {"likely": False, "component": "—"}},
    io_feasibility={"IO1": {"feasible": "yes"}, "IO2": {"feasible": "yes"}, "IO3": {"feasible": "partial", "rationale": "public data minimal, no code"},
                    "io_collapse": "none"},
    notes="Only VERIFY paper with any public original artifact (Zenodo CSV). IO3 partial."))

GOLD.append(paper(
    "zheng2025_male_female_retractions", "Do male leading authors retract more articles than female?",
    "Management_Strategy", "2025", 2025, "DATA-SUB", "Medium", "A/B",
    data=comp(1.0, "Retraction Watch public", data_source="Retraction Watch database",
              data_description="Retracted-article records with author gender", access="public", provenance="Retraction Watch"),
    sample=comp(1.0, "Retraction-Watch sample describable", N="pending", time_window="Retraction Watch coverage",
                unit_of_analysis="article", filter_rules=["gender disambiguation", "leading-author identification"]),
    indicator=comp(0.5, "Gender-disambiguation + retraction-rate metrics; exact pending",
                   formula="Male vs female leading-author retraction rates; gender-disambiguation pipeline",
                   parameters=["gender inference method"], computation_steps=["infer author gender", "compute retraction rates by gender"]),
    model=comp(0.5, "Spec describable; pending", spec_elements=["comparison", "retraction-rate regression"],
               estimator="logistic", coefficients={}, fixed_effects=[]),
    result=comp(0.5, "Gender retraction-rate comparison pending", target_tables=["Tables: retraction rates by gender"],
                target_values=[{"label": "male_minus_female_rate", "value": "pending", "tolerance": "pending"}], expected_direction="positive"),
    claim=comp(0.5, "Claim-result distance moderate",
               conclusion_claims=["Male leading authors retract more articles than female leading authors"],
               claim_scope="general", uncertainty="stated-qualifiers"),
    expected_breaks={"B1": {"likely": True, "component": "sample", "note": "gender-disambiguation substitute"},
                     "B2": {"likely": False, "component": "—"}, "B3": {"likely": False, "component": "—"},
                     "B4": {"likely": False, "component": "—"}},
    io_feasibility={"IO1": {"feasible": "yes"}, "IO2": {"feasible": "yes"}, "IO3": {"feasible": "partial", "rationale": "no original code; agent writes own"},
                    "io_collapse": "none"},
    notes="Mgmt DATA-SUB with public data (Retraction Watch). Tests Sample-component gender-disambiguation."))

GOLD.append(paper(
    "gebhart2023_math_framework", "A Mathematical Framework for Citation Disruption",
    "SoS", "arXiv", 2023, "METHOD", "High", "A/B",
    data=comp(0.5, "APS restricted-access; Nobel dataset (Li 2019) public",
              data_source="American Physical Society bibliographic data (~630K papers) + Nobel laureate dataset (Li et al. 2019)",
              data_description="Physics citation network + Nobel-prize papers", access="partial",
              provenance="APS restricted; Nobel dataset public (Scientific Data)"),
    sample=comp(1.0, "APS sample describable; Nobel set public", N=630000, time_window="1893-2019",
                unit_of_analysis="paper", filter_rules=["APS physics", "Nobel laureate subset"]),
    indicator=comp(0.5, "CD-betweenness-centrality framework; B_k/Π_k measures",
                   formula="Relates CD Index to betweenness centrality; B_k and Π_k disruption measures",
                   parameters=["centrality window"], computation_steps=["build citation graph", "compute betweenness", "relate to CD"]),
    model=comp(0.5, "Mathematical framework + empirical validation; pending",
               spec_elements=["betweenness centrality", "Nobel-discernment regression"], estimator="OLS",
               coefficients={}, fixed_effects=[]),
    result=comp(0.5, "Nobel-discernment mean-rank numerical target exists (B_k/Π_k discern Nobel papers better than CD)",
                target_tables=["Table: Nobel-discernment mean-rank comparison"],
                target_values=[{"label": "nobel_discernment_rank", "value": "pending", "tolerance": "approx"}], expected_direction="positive"),
    claim=comp(0.5, "Centrality-based disruption measures discern Nobel prize-winning papers better than CD Index",
               conclusion_claims=["Betweenness-centrality-based disruption measures outperform CD Index on Nobel discernment"],
               claim_scope="sample-specific", uncertainty="stated-qualifiers"),
    expected_breaks={"B1": {"likely": True, "component": "data_source", "note": "OpenAlex/SciSciNet substitute for APS"},
                     "B2": {"likely": False, "component": "—"}, "B3": {"likely": False, "component": "—"},
                     "B4": {"likely": True, "component": "claim", "note": "centrality-disruption claim on substitute data"}},
    io_feasibility={"IO1": {"feasible": "partial", "rationale": "math framework + empirical target"},
                    "IO2": {"feasible": "partial"}, "IO3": {"feasible": "partial", "rationale": "substitute OpenAlex/SciSciNet for APS"},
                    "io_collapse": "none"},
    notes="NOT pure math — has empirical Nobel-discernment target. Kept as METHOD+empirical."))

GOLD.append(paper(
    "obadage2024_citations_repro", "Can citations tell us about a paper's reproducibility? (ACM FAccT 2024)",
    "IS_Innovation", "ACM FAccT", 2024, "STRICT", "High", "A/B",
    data=comp(1.0, "Public (Zenodo + GitHub)", data_source="ML Reproducibility Challenge 2022 papers + 41,244 citation contexts (Semantic Scholar)",
              data_description="ML papers + citation contexts for reproducibility prediction", access="public",
              provenance="Zenodo 10.5281/zenodo.10895748; GitHub lamps-lab/ccair-ai-reproducibility"),
    sample=comp(1.0, "Public dataset; N explicit", N=41244, time_window="MLRC 2022",
                unit_of_analysis="citation context", filter_rules=["citation-context extraction via Semantic Scholar Graph API"]),
    indicator=comp(1.0, "Citation-context sentiment + reproducibility-score indicators; code public",
                   formula="Citation-context features → reproducibility score (M1-M7 models)",
                   parameters=["sentiment features", "5-fold CV"], computation_steps=["extract citation contexts", "compute sentiment features", "train M1-M7"]),
    model=comp(1.0, "ML pipeline M1-M7; code+notebooks public (MIT)",
               spec_elements=["M1-M5 baseline", "M6/M7 5-fold CV", "tensorflow/keras/torch/transformers"],
               estimator="ML-classifier", coefficients={}, fixed_effects=[], pinned_requirements="requirements.txt"),
    result=comp(1.0, "Table 3 (M1-M5) + Table 4 (M6/M7) numerical targets; notebooks regenerate them",
                target_tables=["Table 3: M1-M5", "Table 4: M6/M7 5-fold CV"],
                target_values=[{"label": "M6_cv_score", "value": "pending-exact-from-notebook", "tolerance": "exact-via-notebook"}],
                expected_direction="positive"),
    claim=comp(1.0, "Claim modest (correlation between citation sentiment and reproducibility)",
               conclusion_claims=["Citation-context sentiment correlates with paper reproducibility"],
               claim_scope="sample-specific", uncertainty="stated-qualifiers"),
    expected_breaks={"B1": {"likely": False, "component": "—", "note": "data+code public"},
                     "B2": {"likely": True, "component": "result_table", "note": "hard-code (low risk given notebooks)"},
                     "B3": {"likely": False, "component": "—"}, "B4": {"likely": False, "component": "—"}},
    io_feasibility={"IO1": {"feasible": "yes"}, "IO2": {"feasible": "yes"}, "IO3": {"feasible": "yes", "rationale": "public data + public code + notebooks"},
                    "io_collapse": "none"},
    notes="Clean-IO3 STRICT anchor (6th). Upgraded from boundary. Identity corrected obadage2023→2024."))

# ===== SLOT #9 REPLACEMENT (VERIFIED) =====
GOLD.append(paper(
    "liu2018_hotstreaks", "Hot Streaks in Artistic, Cultural, and Scientific Careers",
    "SoS", "Nature", 2018, "METHOD", "High", "A/B",
    data=comp(1.0, "Public code + public data in lu-liu/hotstreaks repo (data.zip 85MB)",
              data_source="Career histories: artists (artchive/artnet), directors (IMDb), scientists (Web of Science + APS)",
              data_description="Career impact time-series across 3 domains", access="public",
              provenance="github.com/lu-liu/hotstreaks (code_bursts.py + data.zip)"),
    sample=comp(1.0, "Career histories public in repo", N="pending-exact", time_window="career-spanning",
                unit_of_analysis="individual career", filter_rules=["per-domain split (artists/directors/scientists)"]),
    indicator=comp(1.0, "Hot-streak model + 5 alternative burst functions; KS-test comparison",
                   formula="Hot-streak model (random top-hit ordering) vs (b) right-trapezoid (c) isosceles-trapezoid (d) quadratic (e) tent (f) left-trapezoid; relative position P(Ñ) of top-3 hits within top-6",
                   parameters=["top-k=6", "KS p-value≥0.05 = pass"], computation_steps=["build career impact series", "fit hot-streak + alternatives", "KS test on P(Ñ)"]),
    model=comp(1.0, "Model-fitting + KS goodness-of-fit; code public",
               spec_elements=["hot-streak fitter", "5 alternative burst functions", "KS test"],
               estimator="goodness-of-fit", coefficients={}, fixed_effects=[], pinned_requirements="code_bursts.py"),
    result=comp(1.0, "P(Ñ) distributions + KS p-values; notebooks/code regenerate",
                target_tables=["Fig: P(Ñ) distributions per domain + KS p-values"],
                target_values=[{"label": "hotstreak_ks_pass", "value": "p>=0.05 (green) for all 3 domains", "tolerance": "exact-via-code"}],
                expected_direction="none"),
    claim=comp(0.5, "Claim-result distance small-moderate",
               conclusion_claims=["Hot streaks are a real phenomenon across artistic, cultural, and scientific careers; the hot-streak model reproduces the randomness in top-hit ordering that alternative models cannot"],
               claim_scope="general", uncertainty="stated-qualifiers"),
    expected_breaks={"B1": {"likely": False, "component": "—", "note": "data+code public"},
                     "B2": {"likely": True, "component": "result_table", "note": "hard-code KS p-values (low risk given code)"},
                     "B3": {"likely": False, "component": "—"}, "B4": {"likely": False, "component": "—"}},
    io_feasibility={"IO1": {"feasible": "yes", "rationale": "model described in paper"},
                    "IO2": {"feasible": "yes"}, "IO3": {"feasible": "yes", "rationale": "public data + public code (code_bursts.py + data.zip)"},
                    "io_collapse": "none"},
    notes="Replacement for traag2025 (slot #9). VERIFIED clean IO3: lu-liu/hotstreaks repo contains code_bursts.py (14KB) + data.zip (85MB). SoS, METHOD with numerical KS targets."))

# ===== SLOT #20 REPLACEMENT (VERIFIED) =====
GOLD.append(paper(
    "arts2021_patent_nlp", "Natural language processing to identify the creation and impact of new technologies in patent text: Code, data, and new measures",
    "Management_Strategy", "Research Policy", 2021, "METHOD", "High", "A/B",
    data=comp(1.0, "Public USPTO patent data on Zenodo (static, non-API)",
              data_source="All USPTO utility patents granted up to May 2018",
              data_description="Full-text US patent claims/descriptions for NLP novelty+impact+breakthrough indicators",
              access="public", provenance="Zenodo 10.5281/zenodo.3515985 (static bulk)"),
    sample=comp(1.0, "USPTO utility patents to May 2018; awards-linked validation subset",
                N="all USPTO utility patents to 2018-05", time_window="USPTO coverage to 2018-05",
                unit_of_analysis="patent", filter_rules=["utility patents", "award-linked case-control subset"]),
    indicator=comp(1.0, "NLP novelty + impact + breakthrough indicators; code public",
                   formula="NLP-based novelty/impact/breakthrough measures on patent text; validated vs classification+citation baselines",
                   parameters=["n-gram/term extraction", "award case-control validation"],
                   computation_steps=["extract patent text", "compute NLP novelty/impact", "validate vs awards"]),
    model=comp(1.0, "Case-control validation; code public (sam-arts/respol_patents_code, Python)",
               spec_elements=["case-control", "NLP indicators", "baseline comparison (classification+citations)"],
               estimator="case-control", coefficients={"award_identification_rate": 0.73}, fixed_effects=[],
               pinned_requirements="github.com/sam-arts/respol_patents_code"),
    result=comp(1.0, "73% award identification rate + case-control validation targets; code regenerates",
                target_tables=["Tables: case-control validation, indicator-vs-baseline"],
                target_values=[{"label": "award_identification_rate", "value": 0.73, "tolerance": "exact-via-code"}],
                expected_direction="positive"),
    claim=comp(0.5, "Claim-result distance small-moderate",
               conclusion_claims=["NLP on patent text identifies creation and impact of new technologies better than classification+citation baselines"],
               claim_scope="general", uncertainty="stated-qualifiers"),
    expected_breaks={"B1": {"likely": False, "component": "—", "note": "data+code public"},
                     "B2": {"likely": True, "component": "result_table", "note": "hard-code 73% rate (low risk given code)"},
                     "B3": {"likely": False, "component": "—"}, "B4": {"likely": False, "component": "—"}},
    io_feasibility={"IO1": {"feasible": "yes", "rationale": "NLP method described in paper"},
                    "IO2": {"feasible": "yes"}, "IO3": {"feasible": "yes", "rationale": "public static data (Zenodo) + public code (GitHub)"},
                    "io_collapse": "none"},
    notes="Replacement for zheng2025_social_media_retraction (slot #20). VERIFIED clean IO3: Zenodo 10.5281/zenodo.3515985 (static bulk USPTO data) + github.com/sam-arts/respol_patents_code (Python). USPTO-based, Mgmt/Strategy (KU Leuven dept of management, strategy and innovation). NOTE: 3rd KU Leuven/Arts paper (#6 arts2021, #11 schaper2025) — near-duplicate of #6 but distinct load-bearing component (novelty/impact/breakthrough vs claims-structure); write-up caveat."))

# ===== HELD REPLACEMENT SLOT =====
HELD = []

def main():
    doc = {
        "version": "v1-frozen",
        "date": "2026-06-29",
        "frame": "v7.2 (IO → ECRF → TCE)",
        "n_papers_stable": len(GOLD),
        "n_slots_held": len(HELD),
        "annotation_status": "draft_primary frozen — awaiting 2nd annotator (B) + adjudication for R121 completion; pool composition STABLE",
        "fidelity_scale": {"1.0": "FULL", "0.5": "PARTIAL", "0.0": "NONE"},
        "frozen": True,
        "note": "gold_fidelity = gold-side CEILING (best reachable given observability), NOT agent achieved score. Fields marked 'pending' await human-annotator confirmation (R098 adjudication style). POOL STABLE: 20/20 slots filled (#9 liu2018_hotstreaks, #20 arts2021_patent_nlp, both verified clean IO3). 2-annotator adjudication still required before R122 launch (component-stratified α ≥ 0.70).",
        "stable_papers": GOLD,
        "held_replacement_slots": HELD,
    }
    OUT.write_text(json.dumps(doc, indent=2, ensure_ascii=False))
    # readiness table
    print(f"Wrote {OUT}")
    print(f"Stable papers: {len(GOLD)} | Held slots: {len(HELD)}")
    # overall ECRF distribution
    import statistics
    overalls = [p["overall_gold_ecrf"] for p in GOLD]
    print(f"overall_gold_ecrf: mean={statistics.mean(overalls):.3f} min={min(overalls):.3f} max={max(overalls):.3f}")
    # per-paper one-line
    for p in GOLD:
        print(f"  {p['paper_id']:32s} {p['domain']:18s} {p['observability_stratum']:6s} {p['task_type']:11s} gold_ecrf={p['overall_gold_ecrf']:.2f}")

if __name__ == "__main__":
    main()
